default: &default
  adapter: postgresql
  encoding: unicode
  prepared_statements: false
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: localhost
  database: access_pdf_development

test:
  <<: *default
  host: localhost
  database: access_pdf_test

production:
  <<: *default
  url: <%= CGI.unescape(ENV['DATABASE_URL']) if ENV['DATABASE_URL'] %>
  connect_timeout: 5
  checkout_timeout: 10
  variables:
    statement_timeout: 10000 # 10 seconds
