# python_components/.overcommit.yml
verify_signatures: false
concurrency: 1

PreCommit:
  PythonFlake8:
    enabled: true
    command: ['flake8']
    flags: ['--max-line-length=100']
    include: '**/*.py'

  PyTest:
    enabled: true
    command: ['pytest']
    include: '**/*.py'

  Black:
    enabled: true
    command: ['black']
    flags: ['--check']
    include: '**/*.py'

  Pylint:
    enabled: true
    command: ['pylint']
    include: '**/*.py'

CommitMsg:
  CapitalizedSubject:
    enabled: false

PrePush:
  PyTest:
    enabled: true
    command: ['pytest']

  CustomSnykCheck:
    enabled: true
    required: true
    description: 'Running Snyk security checks for Python'
    command: ['bash', '-c']
    flags: ['
      exit_code=0;
      echo "🔍 Running Snyk security checks for Python components...";
      snyk test --file=requirements.txt --fail-on=upgradable || exit_code=1;
      snyk code test . || exit_code=1;
      if [ "$exit_code" -ne 0 ]; then
        echo "❌ Push blocked due to Python security issues";
        echo "Run snyk test or snyk code test manually to see detailed reports";
        exit 1;
      fi;
      echo "✅ Snyk security checks passed";
      exit 0']
